### ISSUE TITLE
Recent Articles 

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#14]
@paul-headington I’ve been adding a line space between the heading and the first para, as it just looks a little cleaner. Unfortunately this means that the recent articles section doesn’t pull copy the copy through as it seems to just see the blank space. Are you able to either automatically start the first para down a line space on these pages (see http://simpsonwestern.ap-southeast-2.elasticbeanstalk.com/business-law/article-one/  VS  http://simpsonwestern.ap-southeast-2.elasticbeanstalk.com/business-law/commercial-contracts/ to see the difference) so that it still pulls in automatically into recent articles OR just allow the recent articles to pull copy from the first para when it’s on the second line? Just whatever is easiest.

**Comment by paul-headington** [comment]
the system pulls thru the content and then has to pull out the first html tag, so if you start with a space element that will be pulled thru. This is not a trivial thing to change. 

What I suggest is that I add a summary copy field in the CMS so you can enter separate text for each article.

**Comment by michaellevans** [comment]
Yep that’s fine mate – whatever is easiest.

**Comment by paul-headington** [comment]
this is now controlled by a seperate text area called summary
