### ISSUE TITLE
Sidebar links (newsletter & read latest issue)

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#16]
We have these as links in sidebars for this but currently they don’t go anywhere. Is there a page for this somewhere?

Same goes for quarterly newsletter – I’m guessing this is because they haven’t got one yet. Can this just link to the helpful reading page? 

Also where do I make changes to this are?

**Comment by michaellevans** [comment]
![image](https://cloud.githubusercontent.com/assets/26235269/23635977/b671b022-0337-11e7-8765-e21d7e86b6e9.png)

**Comment by paul-headington** [comment]
I've added two Extra Link fields to the admin to control where these go.

**Comment by michaellevans** [comment]
@paul-headington thanks for adding these. We may still need to build a subscription page as linking to helpful reading isn't really the best user journey here. I'll try avoid it though. 

Question: where do these email addresses go? Can't find a DB anywhere.
