### ISSUE TITLE
Our People

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#19]
In the menu, they are going to struggle to decide who to put in there. So can we please remove the + from our people in the menu.

**Comment by DavidQuick71** [comment]
I unticked the show in menu on each of the profiles in the settings of CMS backend. This removed the + and people from the menu. Is there anything else needed so that option isn't ticked when the client adds profiles?

**Comment by michaellevans** [comment]
Can we just ensure it’s unticked for all new profiles when they set them up? Or just remove that as an option?

**Comment by DavidQuick71** [comment]
That's what I was confirming, sorry I should have addressed this to Paul.

**Comment by michaellevans** [comment]
No worries!

**Comment by paul-headington** [comment]
sure thing that default is easily set.

**Comment by michaellevans** [comment]
@paul-headington Menu is still showing the plus and drops down of staff: 
![image](https://cloud.githubusercontent.com/assets/26235269/23929942/0f6942ce-098e-11e7-8a5e-7bb5edc5bc04.png)

**Comment by paul-headington** [comment]
Sorry, I believe the dev thought as it was a CMS content control fix that you would turn them off.

I've done so now via the CMS
