### ISSUE TITLE
Our People – detail pages

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#20]
In each of the profiles we have their mobile numbers – turns out they have a policy of not giving these out the public (who naturally feel they can call their lawyers at any time). So we need to remove the mobile option. 

Also rather than having live email addresses (which can cause spam issues) can we have an HTML link that opens the users default email client? So you would see Email: Click to email same goes for the PA email.

**Comment by DavidQuick71** [comment]
I removed the mobile number as an option. 

As for the email, link option, would they just want an empty mailto link? Not sure what they mean here.

**Comment by michaellevans** [comment]
Hi – just a mailto link rather than the actual email. So embed the email address in the copy. Does that make sense?

**Comment by michaellevans** [comment]
![image](https://cloud.githubusercontent.com/assets/26235269/23929791/451632b6-098d-11e7-87f3-c785923714a8.png)

@paul-headington Please add a space between Email: and Click to email.

**Comment by michaellevans** [comment]
Also the linkedin link has dropped to the second line, the whole thing is starting to look a little messy. Are we just able to make each of the headers hyperlinks? so Phone, Email, PA & LinkedIn are all just hyperlinks rather than headers. Let me know what you think.

**Comment by paul-headington** [comment]
You can make the titles all links, but I feel it would look strange, just a list of titles with just the assumption of a user knowing to click
