### ISSUE TITLE
Sharper logo, phone icon and favicons

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#22]
Please find favicon and new logos attached for upload. 

[favicons.zip](https://github.com/DownTheRabbitHole-io/SimpsonWesten/files/822960/favicons.zip)
![simpson western primary logo_website_rgb](https://cloud.githubusercontent.com/assets/26235269/23636421/30d03bca-033a-11e7-8be4-4c6c30e43fe0.png)
![telephone icon](https://cloud.githubusercontent.com/assets/26235269/23636422/30d64542-033a-11e7-9503-6344a13eea56.png)

I used a generator for the favicons - let me know if any issues.

**Comment by michaellevans** [comment]
@paul-headington or @DavidQuick71 have these all been uploaded? Favicon isn't showing on Chrome.

**Comment by michaellevans** [comment]
@paul-headington can you please come back on these issues.

**Comment by paul-headington** [comment]
they were added, but you favicon code was generated without the html insert file, so I've created and added.
