### ISSUE TITLE
Menu scroll

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#24]
On the menu, you can't can’t scroll through the subcategories for Business & Personal Law sections when they pull down. The page scrolls rather than the menu items. 

Also tap doesn't seem to be working on the menu.

**Comment by paul-headington** [comment]
the fix for this is to make the menu not floating at the top of the page. The float setting means you can never scroll down.

**Comment by michaellevans** [comment]
I’ll try get this over the line, but they may well push back. Fingers crossed.
