### ISSUE TITLE
People filter

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#25]
Some staff work across more than one team and office. So we need to be able to add them to as many the TEAM and OFFICE Filters as possible. It may need to be a list with check box in their profile?

**Comment by paul-headington** [comment]
easiest way is to add a "both,many,all" office/team option in the cms and then select that for those users.

**Comment by michaellevans** [comment]
Can you elaborate on that a little? Not quite following. If it help, in their words: "Need to be able to allocate staff to multiple offices and practice areas, can currently only choose one from the drop down"

**Comment by paul-headington** [comment]
What I'm suggesting is we add an extra option to each drop down called something like "Both or Many, or All" then that can be selected against people who are across multiple offices/teams
