### ISSUE TITLE
Contact VS Find Us

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#26]
When using it they found this confusing, having two areas for this action. I can sympathise with this. I'm putting a wireframe together to see what can be done. Haven't promised to do it in scope as they did sign it off.

**Comment by michaellevans** [comment]
[SW Contact page.pdf](https://github.com/DownTheRabbitHole-io/SimpsonWesten/files/884415/SW.Contact.page.pdf)

**Comment by michaellevans** [comment]
I've used elements from what has already been done. Let me know what you think.

**Comment by paul-headington** [comment]
again we did discuss with them having this on two or one page. I can probably combine into one page if we don't change the layout and just put one above the other.

is that what the box with Contact on your mockup is for?

**Comment by michaellevans** [comment]
Ok cool. yeah the mockup is just pulling elements from each page into one. So hopefully it's just a case of rearranging and then removing the 'Find us' link from the footer?

**Comment by michaellevans** [comment]
As per updated layout: 
1. plese put enquiries email under contact us on rhs
2. please update the addresses as per the addresses in the layout (no Apollo Drive anymore, this is updated with a POBox which is not clickable).

**Comment by paul-headington** [comment]
sure, those are all CMS values, I've updated

**Comment by michaellevans** [comment]
ah sorry I didn't realise. Thanks

**Comment by paul-headington** [comment]
no probs, I should have updated it
