### ISSUE TITLE
Carousel header

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#28]
They want a carousel header. 3-5. Let me know as this was apparently discussed at the beginning. I don't have the history so they're holding it over me. Maybe just the same module as ClickClack?

**Comment by paul-headington** [comment]
hmmm, the more I read thru these tickets the more I see what is happening. It seems that when we had a meeting with a wider team at Simpson Western, ideas were tossed around and now everyone's own interpretation of general ideas is being taken down as agreed functionality.

I'm happy to help out to keep the client happy, but this functionality is clearly no where in and documentation.

The simplest thing I can do is just put a static image carousel with the same fixed size as the existing top image on the home page. I can reuse some of the ClickClack code and it should  only take 4-5hrs.

**Comment by michaellevans** [comment]
Ok thanks. Please put a quote together line by line. We can then visit it with client and see what they actually want to bite off. So difficult as well as I wasn’t there!

**Comment by michaellevans** [comment]
Not sure if this has been done. Looks like they still only have one option.

**Comment by paul-headington** [comment]
sorry I thought this was taken out of the extra's quote. I can put it back in.

**Comment by michaellevans** [comment]
Sorry definitely got wires crossed here. what is the dollar cost on this so I can update quote?

**Comment by paul-headington** [comment]
I've updated the quote and sent you a new copy. @ 4 hrs it comes out at $600 +gst

**Comment by paul-headington** [comment]
done
