### ISSUE TITLE
Newsletter signup

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#29]
This needs to sync with their mailchimp account:

 login details:
 
User:     simpsonwestern
P/W:      ##57Byron

**Comment by michaellevans** [comment]
Let me know hrs on this as it's not in scope.

**Comment by paul-headington** [comment]
that's fine, this hook up was in my quote

**Comment by michaellevans** [comment]
cool.

**Comment by michaellevans** [comment]
hi can you please confirm what list this is syncing with in Mailchimp?

**Comment by paul-headington** [comment]
yes it is

**Comment by michaellevans** [comment]
I can't see where sorry can you please confirm?

**Comment by paul-headington** [comment]
I've given it a new name so it's more obvious

<img width="1284" alt="screen shot 2017-05-01 at 12 29 09 pm" src="https://cloud.githubusercontent.com/assets/2722637/25569348/d5ce4d38-2e69-11e7-8d7c-401ad4bf01b4.png">
