### ISSUE TITLE
Remove image upload and text editor from helpful reading / Main Content tab in CMS as it's confusing. 

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#31]
![image](https://cloud.githubusercontent.com/assets/26235269/24535294/98279c70-162f-11e7-892c-f52ccc62fa11.png)

**Comment by paul-headington** [comment]
These elements are part of the standard page inherited by the blog module, which just doesn't get used in the helpful reading view. hiding them requires a custom override which is a significant amount of work 4-6hrs. Didn't seem worthwhile but we can if this is a major issue.
