### ISSUE TITLE
Product Pages - Our people widget

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#33]
The staff profiles that turn up on the right of each product page (see below) are a bit long. CAn we revise this to just the height of the profile thumbnail, with their name and their position to the right? That way they can fit way more in without going too deep. 

![image](https://cloud.githubusercontent.com/assets/26235269/24536395/a1286a8c-1636-11e7-8601-92b1dd5fade4.png)

**Comment by paul-headington** [comment]
That copy is controlled by the field "short text" in the profile page profile tab. You can shorten it as much as you like.
