### ISSUE TITLE
New logo and phone icon attached for upload. 

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#34]
![sw_logo_240px_x_18px_v1](https://cloud.githubusercontent.com/assets/26235269/24536547/9a448074-1637-11e7-9ab2-ce103b62d935.png)
![sw_phone_44px_x_29px_v1](https://cloud.githubusercontent.com/assets/26235269/24536546/9a2c7aec-1637-11e7-9a30-798c99f02911.png)

I'll email them as well.

**Comment by michaellevans** [comment]
Can you please confirm if this has been done? Still the old phone on there. Not sure about the logo.

**Comment by paul-headington** [comment]
yes this has been done, the phone still had my icon test on testing for you, I'll revert it to the images

**Comment by michaellevans** [comment]
Hi - really sorry. New phone sucks. Let's go back to your one please.

**Comment by paul-headington** [comment]
ok
