### ISSUE TITLE
Advisor profiles

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#37]
Need to link in Legal Advisor Profiles onto main Business and Personal Law pages (right-hand sidebar)

**Comment by paul-headington** [comment]
not sure what this means, profile pages already link to articles pages and vice versa?

**Comment by michaellevans** [comment]
Sorry mate to be clear: Need to be on the rhs of the two actual category pages: 
http://simpsonwestern.ap-southeast-2.elasticbeanstalk.com/business-law/
http://simpsonwestern.ap-southeast-2.elasticbeanstalk.com/personal-law/

**Comment by paul-headington** [comment]
sure that won't be a problem

**Comment by michaellevans** [comment]
Hi still need to add the ability to put staff profiles on these two pages. Working really well everywhere else, just need the same for these two.

**Comment by paul-headington** [comment]
you sure can, just have to choose who you want in the cms in the same way as the other pages

![screen shot 2017-04-26 at 4 31 13 pm](https://cloud.githubusercontent.com/assets/2722637/25418173/db68f0d8-2a9d-11e7-8ac6-22ae7a3e776a.png)

**Comment by michaellevans** [comment]
Ruddy good.

**Comment by paul-headington** [comment]
I added a couple so it looks populated. The same field works in blog posts too to add people links.
