### ISSUE TITLE
Linkedin Links

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#39]
Linkedin addresses are long, they drop a line then split over two lines, looks messy – can we treat like the email where the URL is hidden behind a hyperlink?

**Comment by michaellevans** [comment]
Please change 'LinkedIn' to 'Click Here'

**Comment by paul-headington** [comment]
![screen shot 2017-04-28 at 4 23 41 pm](https://cloud.githubusercontent.com/assets/2722637/25514174/14c2fddc-2c2f-11e7-8aa0-a97fc19d6333.png)

this is done
