### ISSUE TITLE
Text editor - add another font size option

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#40]
Need to introduce another level of text (intro level > paragraph) at the moment there seems to only be one size (paragraph) for body copy, not a great visual hierarchy on the page.

Please make this three point sizes bigger than the current para size.

**Comment by paul-headington** [comment]
I can add, but I've noticed most of the current levels of title styles aren't being used and titles are just bold para copy in their own paragraph. Do we need to remove some of the 7 tiers of body copy already in place?

**Comment by michaellevans** [comment]
Hey mate,

This is what we have at the moment in the text editor, from what I can tell:




[cid:image001.png@01D2B20A.2A72A820]

I’d say that preformatted isn’t really going to be used. ‘Address’ is an interesting one as it looks italicised in the text editor but is really just a smaller version of the paragraph font.

So yeah I reckon replace Preformatted with a bigger font size Paragraph option?

**Comment by paul-headington** [comment]
I see, those are not styles but html markup elements. The styles are in the box to the left of that see below:

![screen shot 2017-04-11 at 2 18 34 pm](https://cloud.githubusercontent.com/assets/2722637/24890065/cbea7d3a-1ec1-11e7-850d-0363f6d89eda.png)

**Comment by michaellevans** [comment]
I only get one style option?

[cid:image001.png@01D2B2D9.EB09C8A0]

**Comment by paul-headington** [comment]
your screenshots are not coming thru from email

**Comment by michaellevans** [comment]
I only get the option for a T1 style in the text editor.

**Comment by paul-headington** [comment]
the styles are displayed as per they appear on the site the first one t1 is huge and takes up the whole first row. Try scrolling down the list.

**Comment by michaellevans** [comment]
Ah bloody good. Thanks. That should be more than enough for them. Sorry, that was so obvious.

**Comment by michaellevans** [comment]
Ok, so specifically, this is what she needs: 

Can we please just have an extra paragraph style (or whatever it is you call it where you select, heading 1, heading 2, etc) that is the same size as paragraph but a heavier weight font.

It looks like paragraph is Gibson Light, so just the next level up Gibson Regular.
I would like it to just look like the attached.
[SW WEBSITE TEXT EXAMPLE.pdf](https://github.com/DownTheRabbitHole-io/SimpsonWesten/files/931845/SW.WEBSITE.TEXT.EXAMPLE.pdf)

**Comment by michaellevans** [comment]
Can you comment to confirm what the styles or paragraph options accommodate this change?

**Comment by paul-headington** [comment]
sure new style para-bold

**Comment by michaellevans** [comment]
Not seeing that as a style - or are you saying use the paragraph but bold it in text editor?

**Comment by paul-headington** [comment]
hmmm, I've definitely added it, I'll look into why it's not showing up.
