### ISSUE TITLE
HEader spacing

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#41]
Spacing after some headings too tight – this page is good: http://simpsonwestern.ap-southeast-2.elasticbeanstalk.com/personal-law/seniors-planning/  
spacing under Asset Planning – but main heading spacing under 'Plan it your way' is too tight. Need to expand please.

**Comment by michaellevans** [comment]
Hi where abouts can I review this change? When I look at anything under personal / business law the spacing between header and body copy is still too tight: http://simpsonwestern.ap-southeast-2.elasticbeanstalk.com/personal-law/

**Comment by paul-headington** [comment]
you can review on http://simpsonwestern.ap-southeast-2.elasticbeanstalk.com/personal-law/seniors-planning/ 

I see on the page personal law parent page, the content has been entered without using the defined copy styles.

I can add some margin to that too, but as this is a CMS controlled site I can style every possible combination of copy entry.

**Comment by michaellevans** [comment]
Yep that's fine - all I want is a default spacing across all of them. The issue is that all of these have a single space after the T2 header. adding a double space after the header like i've done here: http://simpsonwestern.ap-southeast-2.elasticbeanstalk.com/personal-law/article-two-2/
 is too much of a space. So it's messy. Ideally a single space under that T2 header would allow for a better spacing for the following paragraph text?

**Comment by paul-headington** [comment]
Sure I get it, I've added the spacing under t2 and and one using just a plain h2 without styling.
