### ISSUE TITLE
Side panel profiles - uneven

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#44]
Please make the spacing between each of the staff profiles in the side panel equal. In the example below the distance between brian and the line below is good. But overall just need to be consistent. 

![image](https://cloud.githubusercontent.com/assets/26235269/25508244/e5024d34-2c04-11e7-8127-3eb53111cce4.png)

**Comment by paul-headington** [comment]
sure
