### ISSUE TITLE
Staff profiles in side panel

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#47]
Spacing between staff profiles still isn't consistent. Looks like it might just be the top of the first one? 

![image](https://cloud.githubusercontent.com/assets/26235269/25648930/0bc43a80-3025-11e7-8bb5-db77395ae755.png)

**Comment by paul-headington** [comment]
ok I see what the issue is.

**Comment by michaellevans** [comment]
Just jumping back into this one - please have another look as the job title has shifted down since our last update.

![image](https://cloud.githubusercontent.com/assets/26235269/25790315/b4434c84-340b-11e7-80fa-c8b14469d989.png)

**Comment by paul-headington** [comment]
Ok, that's due to added the extra spacing to the standard heading tags instead of having them use the styles we made. I'll add an exception to fix.
