### ISSUE TITLE
Assign blank images to staff profiles

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#48]

**Comment by paul-headington** [comment]
Please provide a blank image that you'd like to use

**Comment by michaellevans** [comment]
Assigned this one to myself. Unless you need to do it so that they stay when we push to new server?

**Comment by paul-headington** [comment]
no it's purely done via the CMS.

I've made a assets folder backup so we can transfer them to the new server

**Comment by paul-headington** [comment]
hang fire on this for a second as I'm pushing these updates up as we speak

**Comment by paul-headington** [comment]
ok done, the people all need and image, name and a job title to make sure they display correctly.

**Comment by michaellevans** [comment]
Ok thanks.
