### ISSUE TITLE
Business and Personal law pages

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#50]
There is some slightly different styling and copy in the side panel of these two pages: "We publish a free quarterly newsletter for our business clients."

It's too close to the line above it and not really needed - can you jsut use the same styling and copy that goes in it's place on all the other sub pages? 

![image](https://cloud.githubusercontent.com/assets/26235269/25790510/364e97c8-340d-11e7-9165-67c19c9258cc.png)

**Comment by paul-headington** [comment]
sure, done

**Comment by michaellevans** [comment]
Sorry they've asked for it to just be the same copy as the screen grab above. Should have made that clearer.

**Comment by paul-headington** [comment]
ok

**Comment by paul-headington** [comment]
ok done
