### ISSUE TITLE
Profile orders

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#51]
There may be a wee bug with the ordering of staff profiles in the side panels. For example, we're trying to get Jamie to appear after Ken in the commercial property page 

http://preview.simpsonwestern.co.nz/business-law/commercial-property/

however when I write them in, in that order, it shifts Jamie back to the middle. 
![image](https://cloud.githubusercontent.com/assets/26235269/25791159/a35431d4-3412-11e7-9b28-fb5a73a36ae0.png)

In other areas it's allowed us to dictate the order (like the employment page), but not on the above?

**Comment by paul-headington** [comment]
no you're right there is no ordering in linked profiles. any ordering you have so far is just a coincidence.  The order will be being pulled from the page order in the tree as that is the order we added in a past task so that profiles could be ordered.
