### ISSUE TITLE
Recent articles = blog

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#52]
Confirmation on Recent Articles linking from client - three key points:

1. It should definitely be Recent Articles pulled from the blog section.
Doesn’t make sense to pull them from service offering pages as there will be little/no change to these for anything to become more recent than anything else. 
These pages will be there from the start and hardly ever changed.

If we can please link 3 most recent articles onto Home, About Us and Our People pages.

2. BIG question for Our People page is when it is displaying all the people, I assume it would show just the 3 most recent articles overall – BUT what happens when you filter it down to just commercial?
Will it show just the 3 most recent articles related to commercial? 

3. Lastly beside the people profiles it needs to be the 3 most recent articles linked with those individuals.

**Comment by michaellevans** [comment]
Some rules to adhere to:

1. Please change the name from 'Recent Articles' to 'Related Articles'
2. Limit of three related articles tagged to that profile
3. Chronological - as a new one is tagged to that profile, the fourth most out of date article is dropped.

**Comment by michaellevans** [comment]
4. Ensure the side banner pulls the custom summary text.

**Comment by paul-headington** [comment]
sure, this is a significant change but should be doable by Friday.

**Comment by paul-headington** [comment]
ok done, The home page title has been left as "Recent" as it makes no sense there related to what?

plenty of summary copy needed in the CMS

and not it's always just the 3 most recent articles related to the profile (on the profile page) and the 3 most recent articles on all other pages.

**Comment by michaellevans** [comment]
Perfect – thanks mate.
