### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#53]
Painful page this one. 

1. I need to add postcodes into the physical addresses but can't see where to do this - only seem to be able to update the PO Box details? Can you confirm?

2. She's stuck on the alignment between Get in Touch and Contact us to the right. Are we able to align the headers and body copy? i.e. Getting the Contact us on to sit on the same line as Get in touch and the phone number to sit on the same line as the first line of text (For exceptional legal advocacy and…) 

This sounds very similar to that original alignment conversation we had on the homepage.

**Comment by michaellevans** [comment]
3. We also need to add specific phone number and fax to each of the physical addresses. Client is going to send a PDF design of preferred tweaks.

**Comment by michaellevans** [comment]
4. Can we please tighten the spacing between the address header and address location details (will be in supplied layout later today).

**Comment by paul-headington** [comment]
sure

**Comment by michaellevans** [comment]
PDF of design feedback on Contact page... 
[Contact.pdf](https://github.com/DownTheRabbitHole-io/SimpsonWesten/files/988658/Contact.pdf)
![screen shot 2017-05-10 at 2 07 12 pm](https://cloud.githubusercontent.com/assets/26235269/25882752/d770b3d8-3599-11e7-85bd-ced843a04b9d.png)
![screen shot 2017-05-10 at 3 53 53 pm](https://cloud.githubusercontent.com/assets/26235269/25882753/d771f5fe-3599-11e7-8fdc-7de9cbd645d1.png)

**Comment by michaellevans** [comment]
PDF of design feedback on Contact page...
[Uploading Contact.pdf…]()
![screen shot 2017-05-10 at 3 53 53 pm](https://cloud.githubusercontent.com/assets/26235269/25882780/fff2fc26-3599-11e7-83f4-ad0eb5d30082.png)

**Comment by paul-headington** [comment]
you can't micro manage the alignments on this that much, it's a contact editable site. I had it lined up before and then they entered new content using different font sizes.

The Postal address is a page editable value the location addresses come from the single offices data which gets used thru out the site. the "content" field against an office is used for this copy. the address (no line breaks ) is used in the maps pop up .

I've added a seperate phone fax field and reworked the margins
