### ISSUE TITLE
Black copy vs charcoal

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#54]
Some bits of text are black #0000 in the inspector/developer tools, and others a dark charcoal (#333541) - all text aside from sidebars were meant to be black.
Eg Heading 1 is black. Heading two is #333541.

IF it is only Heading 1 with black allocated to it perhaps it’s just best to change that to the charcoal (#333541)…

**Comment by michaellevans** [comment]
Check out Gregg's page for why it can be an issue: http://preview.simpsonwestern.co.nz/our-people/greg-woodd/

So best to change it all to black I think

**Comment by paul-headington** [comment]
ok Think I've got them all

**Comment by michaellevans** [comment]
Hey I’ve checked the first three and none seem to be on the staging site – can you check these have been pushed through?
