### ISSUE TITLE
Blog alignments

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#55]
The heading lengths have to be quite short to fit, which they can sort of manage but there is an in between point where the text wraps and disappears – see screenshots attached.

Also the blog seems to start a bit low, i.e. All the other pages line up with the start point of the side bar – at the moment the first line of text sits below the start of the right column (our people associated with the blog topic).
![screen shot 2017-05-09 at 1 15 38 pm](https://cloud.githubusercontent.com/assets/26235269/25876395/f9da13ac-3570-11e7-8d89-a673584f5f0f.png)
![screen shot 2017-05-09 at 12 55 46 pm](https://cloud.githubusercontent.com/assets/26235269/25876394/f9d8533c-3570-11e7-9bcf-6cc143a35ad4.png)
![screen shot 2017-05-09 at 12 55 54 pm](https://cloud.githubusercontent.com/assets/26235269/25876397/f9dadd46-3570-11e7-94f5-5c732d99e748.png)
![screen shot 2017-05-09 at 12 56 02 pm](https://cloud.githubusercontent.com/assets/26235269/25876396/f9da7fea-3570-11e7-976c-372bb4269196.png)

**Comment by michaellevans** [comment]
Can we change the width (just for the blog) of the break point for the headers to the full width of the page?

**Comment by paul-headington** [comment]
sure, there will still be a max copy length tho

**Comment by paul-headington** [comment]
done, max length set to this title "Upcoming changes to employment legislation"
