### ISSUE TITLE
Blog featured article

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#56]
Is pulling the first paragraph of 'paragraph' text from the text editor rather than the text from the Custom Summary. See Buying off the plans. 

it does pull the Custom Summary copy down below in the main page though.

**Comment by paul-headington** [comment]
I can switch it to the custom summary, but that means it will always need to be filled in.

**Comment by michaellevans** [comment]
Yep we can just insist on this. Spoke to her about it earlier so all good.

**Comment by paul-headington** [comment]
done
