### ISSUE TITLE
Menu needs to be a pixel or two wider

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#58]
notice the line down the side: 
![screen shot 2017-05-10 at 2 07 12 pm](https://cloud.githubusercontent.com/assets/26235269/25882814/1a5a9cae-359a-11e7-958a-f51d3b7e8860.png)

**Comment by paul-headington** [comment]
done

**Comment by michaellevans** [comment]
it's still showing - do I need to clear cache or anything?
