### ISSUE TITLE
Menu on moble

### ISSUE THREAD

**Issue by michaellevans** [DownTheRabbitHole-io/SimpsonWesten#61]
I can't tap on sub categories on mobile menu.

**Comment by michaellevans** [comment]
![image](https://cloud.githubusercontent.com/assets/26235269/26038520/5684865a-395e-11e7-8628-ab217cd4b9a8.png)

**Comment by michaellevans** [comment]
Also, the opacity needs to be upped further down when the menu is fully open: 

![image](https://cloud.githubusercontent.com/assets/26235269/26039220/29f58b44-396c-11e7-8fcd-968f68ac2c33.png)

**Comment by paul-headington** [comment]
sorted
